name: Build & Deploy API

on:
      push:
            branches: [main, stage, develop]
jobs:
      build-and-deploy:
            runs-on: ubuntu-latest
            steps:
                  - uses: actions/checkout@v3

                  - name: Configure AWS credentials
                    uses: aws-actions/configure-aws-credentials@v2
                    with:
                          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                          aws-region: us-west-2
                  - name: Log in to ECR
                    id: login
                    uses: aws-actions/amazon-ecr-login@v1


#       - name: Build and push image
#         env:
#           REGISTRY:   ${{ steps.login.outputs.registry }}
#           REPOSITORY: my-app
#           TAG:        ${{ github.sha }}
#         run: |
#           IMAGE_URI="$REGISTRY/$REPOSITORY:$TAG"
#           docker build -t "$IMAGE_URI" .
#           docker push "$IMAGE_URI"
#           echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

# - name: Deploy infrastructure with new image
#   run: |
#     aws cloudformation deploy \
#       --stack-name my-app-infra \
#       --template-file path/to/ecs-ec2-with-api-cf.yml \
#       --capabilities CAPABILITY_NAMED_IAM \
#       --parameter-overrides ImageUri="${{ env.IMAGE_URI }}"
